#pragma once
#define PASSPORT_SSID "YOUR_2_4_GHZ_WIFI"
#define PASSPORT_PASSWORD "YOUR_WIFI_PASSWORD"
#define PASSPORT_HOST "192.168.1.100"
#define PASSPORT_KEY "REPLACE_WITH_THE_SAME_RANDOM_KEY_AS_THE_HOST"
